// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskApi.Data;

#nullable disable

namespace TaskApi.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskApi.Data.Entities.TaskClass", b =>
                {
                    b.Property<int>("ID_TAREFA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TAREFA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TAREFA"));

                    b.Property<DateTime>("DATA")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("STATUS")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("TITULO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITULO");

                    b.HasKey("ID_TAREFA");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
